# This site is built upon jekyll-theme-prologue
# See https://github.io/chrisbobbe/jekyll-theme-prologue for documentation


title: Semestre 6 - Info
subtitle: ENSEIRB-Matmeca
description: >-
  Cours d'informatique du Semestre 6 de l'ENSEIRB-MATEMCA, année 2019/2020
author: Delpeuch Sébastien
email: sebastien.delpeuch@enseirb-matmeca.fr
avatar: assets/images/téléchargement.svg

baseurl: ""
url: "https://sedelpeuch.github.io"

twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url: https://github.com/Sdelpeuch
pinterest_url:
slack_url:
dribbble_url:

google_analytics:

remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
